### PR TITLE
Add CudaManagedMemoryPool rmmAllocationMode.

### PR DESCRIPTION
**Pull request by ZhenshengLee**
This mode is for Jetson devices that support unified memory access with iGPUs(intergrated GPUs).

According to https://github.com/neka-nat/cupoch/issues/26 and https://github.com/neka-nat/cupoch/issues/61 , managed memory allocation is best for jetson devices to get lower memcpy overhead.

According to this comment _Originally posted by @neka-nat in https://github.com/neka-nat/cupoch/issues/60#issuecomment-818434655_ the pointcloud processing time can be reduced with pool allocation with avoidance of dynamic memory allocation

I add a enum that is CudaManagedMemoryPool, currently it is supported by ini function

https://github.com/neka-nat/cupoch/blob/f6c91f429eaa965f7c2b7ee7d400d6086aeee015/src/cupoch/utility/device_vector.h#L81

So, I just added the missing enum. I will give it a test on jetson xavier later

Thanks. @neka-nat

### CODE REVIEW

**Comment by neka-nat** [comment]
Thank you!
Please share the results of the test when you know them.

**Comment by ZhenshengLee** [comment]
> Thank you!
> Please share the results of the test when you know them.

Hi, I give it a test based on this commit https://github.com/ZhenshengLee/perception_cupoch/commit/f7d616f58e3dc71245b8ae1b5ab12d3d59a8c22b

In Jetson Agx Xavier device, and to set cpu frequency.

```sh
# set mode to MAXN
sudo nvpmodel -m 0
# set cpufreq to make every cpu core work at freq of 2.3GHz
sudo cpufreq-set -g performance
```

Note that pcl conversion time is the baseline.

@neka-nat It seems that memory pool is not as effective as the original one.

The result is not what I expected days ago, currently I am confused have no idea about this.

|   | h2d / h2h time(ms)| stable? |
| ------------- | ------------- |---------|
| pcl |  4ms | stable| 
| CudaDefaultAllocation  | 9-12ms |unstable  |
|PoolAllocation  | 7-8ms | stable |
|CudaManagedMemory  | 8ms | stable |
|CudaManagedMemoryPool  | 6-10ms | unstable |

BTW, I cannot use the `nvvp` gui tool as it crashed with java runtime error.

**Comment by ZhenshengLee** [comment]
Track with this issue https://github.com/ZhenshengLee/perception_cupoch/issues/9

**Comment by neka-nat** [comment]
Thanks for the reporting!
I'm curious to see how much the actual memory allocation time decreases.
nvvp may work if JRE version is given explicitly.

```
/usr/local/cuda/bin/nvvp -vm /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java profile.nvp
```

**Pull request merged**
